blank_issues_enabled: false
contact_links:
  - name: AGIME Discord discussion
    url: https://discord.gg/goose-oss
    about: Please ask and answer questions here.
  - name: Report a security vulnerability
    url: https://github.com/fengrui198609/agime/security/policy
    about: Please report security vulnerabilities here.
